name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: HTML check
        run: echo "Static site - no build needed"
